title: Knowledge Discovery Laboratory

# Build settings
markdown: kramdown
theme: minima
# plugins:
# - jekyll-feed
# - jekyll-paginate
# paginate: 5
# posts: _posts
# paginate_path: "/blog/page:num"

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: kdlumass
comments: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Explicitly enumerated here so that we can control the ordering
nav:
  - text: About
    url: /index.html
  - text: People
    url: /people.html
  - text: Publications
    url: /publications.html
  - text: News
    url: /recent_news.html
  - text: Software
    url: /software.html
  - text: Data
    url: /data.html

collections:
  people:
    output: true
  pubs:
    output: true
  posts:
    output: true
  software:
    output: true

authors:
  etosch:
    first: Emma
    last: Tosch

